### PR TITLE
GitHub actions for Windows and Linux

### PR DESCRIPTION
**Pull request by KernelA**
The GitHub action for automatic building on the Windows and Linux.

[GitHub Actions build status](https://github.com/KernelA/cuda_voxelizer/actions/runs/173899372)

### CODE REVIEW

**Comment by Forceflow** [comment]
I'm going to read up a bit on GitHub actions, and will probably merge this later. 

Much appreciated, just gotta wrap my head around it ;)

**Comment by KernelA** [comment]
Ok, i will wait for any comments.

**Comment by KernelA** [comment]
Hi, @Forceflow.

Any update here?

**Comment by Forceflow** [comment]
Sorry :) Merged!

**Pull request merged**
