### PR TITLE
Add implementation of solid voxelization

### PR DESCRIPTION
**Pull request by conceptclear**
Hi,
I have added some functions to achieve solid voxelization according to the paper "Fast Parallel Surface and Solid Voxelization on GPU's". I hope you can merge it if there is a need.

Thanks

### CODE REVIEW

**Comment by Forceflow** [comment]
Hey @conceptclear, this looks interesting.
Some questions before I merge:

- Right now this replaces the non-solid voxelization path - I can convert this into an "optional" path, or you can change your PR - whatever fits your schedule
- Does this work with non-watertight models?

-

**Comment by conceptclear** [comment]
Hi, @Forceflow 
of course, you can do this.
This method is not available for non-watertight models which would cause redundancy or loss of voxels.

**Comment by Forceflow** [comment]
This also needs to be made against the dev branch. I could do it for you, but then you'd lose bragging rights :)

**Comment by conceptclear** [comment]
Haha,
I'll separate the re-push this code later today
Thanks for your advising

**Pull request closed without merging**
